language: java
dist: trusty
os: linux

jdk:
  - openjdk11

cache:
  directories:
    - "$HOME/.m2"

install:
  - mvn --settings .travis/settings.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V

before_install:
    - if [ ! -z "$GPG_SECRET_KEYS" ]; then echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXEC --import; fi
    - if [ ! -z "$GPG_OWNERTRUST" ]; then echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXEC --import-ownertrust; fi

deploy:
  -
    provider: script
    script: .travis/deploy.sh
    on:
      branch: master

env:
 # GPG_EXEC
 - secure: "Gx8fNR3UNMxbQbl56VN0V3e7MljQ7HBRqKMzR62elmKDluwCoPqe/2bV5wHEYM6UkTDGPtWXANjnB2ldqAqCTo9lvgQYmwVNSUJKFFeqxVmpehlc3wtEBuCmwMKA1WjSQm0ZL2DG6kPrNUrMkSzdN80jsye+k9Mr9hRFzYZJlursnNksRvzgV+TtOifZCkIBtTqFp+jxNEYMQMY62TEpxEVl8TdMw+WFVZh35pFziu50r8nuGnoQdW4PfNa4yinMdDY19CD1vmI0/HO09neKyBokrd4C5F4237DuY3bPnfR/n3tHhhWGREqIqSUYCpK5F26n9p1HLHzR+Q8/U/RjTLaxo6mJ34UAumZvNMOQ+LqtL/zeTj1io7akTBrjyV2UyGkF0ybGpk2zsHm/kDYmNeB0pdvzTWAvgfE1fzwxEYjRwZYLSSi8YRwvwT72UMIYf0xx4UUCfaSLsKKfEwVKUpkeUDF/hqeFm3CskntLegjZmaH3XZ/4z1ODWvynkIuw3wr23FzcATDpmr15p9uK7ZJGLKT/dPtG9IGb/OLL/Q6v3RLEciYByDqAFxmIPnZcEyYFwFU3+a3U4qipEDck0cAjyOKk0nVRmDYralgSST7c+f8syTzwjLy7pAxHJ05luNzz3nsA7A844hgcrSTeuBQYX8WSe+OwW86k20aXNSM="

 # GPG_OWNERTRUST
 - secure: "I+7JrE0uf234uvpYCeifkb1fuJslnPwG7I1sJOuRvhatsjIT+CAMbT3TZE0w4WEIVpmSJ+nopMoYomkXQtC8VIcFoZvUIh3E+R4+VXy8K+Om/p2g2ohXPaNYouRS9/6rY/jJPKfE4brnFMUbRUwViE/lmfUl1PPZzPyfhAcgyfrLM9+b2HovZ0sOjkrPjHjS472+O/QJWALBUyezmAeC1ZL2u2c/WIhs+9kNeTwNuDKZTBv7X8mStVU+viDeWr21YxLHdFl0CABp0edOgmI5HaHcHMQB1mMSH8R5z+wLz9dVmsJWPivA0W7gZzryeuiqU4caqug4EhpoTvYhu4Zt4vG0pKKlDXHJNV2rK6yzotBM9DEHcLlzPXGtRFD4pIfiiHlUuEyGZs7BguEGYOsecb2lWazG8ni05yFka/t4JWkTZbpTwOJBavzNlZ2yh0JtPUtXuaSfzIEbMMPWwn4NwQ5kADa7b6fq6MMfI6xD6F82gjKnw1TaBJFkO4aCOIl50CDvJIo/T0c815BE5nvUcljsX5UZSUBeSB797OGB/L0+zdQwgZQGUb1jL1KMIwq/3KGpPEhSVrANyIySmeXoes6efn2L9LdMh/3LkODbxJ1L1Eq9K2+wDljaaTutBOZyCT18W19UiNaCdGV3jx92057+jd7QhgsLrTgNMutRYKk="

 # GPG_PASSPHRASE
 - secure: "O8ES2D6gtp+Eu///L5ysF1ZKjUyEtljY8Z4LmQFvkwPXU2MEmbUgbMqv6qUMnu82P143PVneuStC8xThWzfml40wIZyRRiMmMaY6AEC7OLJOJiMrsP49lExMSKcOwfaIQ9IA0ZmIjP0RIVy0sPx0KhYGIa/EMCbf0vSwQKGQsD8uGy2AMnMqA+1+ZoKeIpokduLbs+PzP4+FVqoSL/xI+T144h2pwLAe5o97iw6omsbB1owroV4u7AJJsJdofb386tquqOeBlAsuSGVXesjQ1/acVTp8jk+6nDFac7iTXEwpYdp46Y+KzJRcIrojE15Pej7GtziCEYBGfPqV2BHgSO0h2ZqxlHrWUKdNIS0xFW5uB5hBcTff2O2FvalmvdCDYPqw0RQV6A5phJKDFaZu7fppKRWusTMHG/CZSb9Y5tRWsGeVugfrym8ihbEJ0ioABQo6G5f+gtDFXyg+20nsEVCR8N1K1TSZ+FYDHy9zFdBbpy7MIMBdec2FYxjtrvcP1gmNrwf2g1Aa0wWNg9dQqX1v9PZMy4hAXM9huUMUIders0tQjFb1yo9NQLjbdCAEYbE7QkY8YjOdSbStM/SF9JPLJbe1OlXeW8pm9O0Tw+i5yp2X4oCFrOop0xxISD4yEloY5ZrgXmS9FKkzGgNIuTluYxjqIy9eCt/X550j8mk="

 # GPG_SECRET_KEYS (set online value too large)

 # NEXUS_PASSWORD
 - secure: "C8VNse7fJpxUxsbu7F73ukN4HW5c/Tb/W3c5hiSFYdkrwWHDncRXl1KyX6qD48cuFKh4Kc7EWaopgtlbtR89ZlsYi5Ii91+yV3BUGxMzFM60n9ggRDhuB6D4qKHrrTHd3MR5boosZuc6+o204e0SmzbMV3xY1MRNl1MZsERujGCjOHazsEeK6jlGE4nDiH4dvCzLHqlnY+JFe2Q8Yo43ZitgG48Grp+XRnNwNTXIC8kPQlzn6FIuTl4dPbr8wOuk/Ak6+/owvQ9Em2WITeeP+tMXp0EhCeHn2hR+TTo9gy+jHalKPPK3DTeimgN5EhvzRJqapy4qephEGCjuUBJo5RP5kO6XrSzS7LU6GbMYk0Vyp9ooAD+/V3UrX3lGIutJ8TNQx0TCy8xJejijal+PyfMzcMxh86fifAGJQGR+qk4jk37dzsgUaniu7xMSvcVjsCIqc3Dd3BJbJsOKAPW0hYnQoRK6FfTYAGu9NL9ZIHFUWY/G4HYH94Xxix/dejcrnkirEeF91a4QMFMcmVuXfbR+2lPtLOvC4DX1A++/Bz+y6gon31r8VAGdkndha3L162MixpPJxULxUTEVQ7LkUiQbqWzouXx0dilvacV6ZZ8SENNB0hJHpce84JbJ0FsZZCTyRKy5J40fj9ITMlijr+hRPFUOaQHo6pHW6PAjmwE="

 # NEXUS_USERNAME
 - secure: "TuWsiwpEsNdyQXoSYcpLE48PHmpxjdB2urcp9D9bZdmw3bpvpOr6P2LUDte97sghCD7C40QGxb6Crrzd/HK5MEHzc6yiOKs2AQd9X9/6wEssXI6apHF/t+Cw+f9v3FfWKj6J+VPfgW2B8lx8WmRsgNuk8DKS/EQBAWo1uaexSSqP7lN6IODYFqPw6KjF/RuozU9JFsaXjFD2+/EhAKMyRfAAE9UxTlr7oYF/qdO5M6M3s3uCx6hzMDH9p6X9v7eHAfCWf6K1h+utDqmirUuU+NDU9GMTYH8xiR8AZwsY0vb/xNABp0QiBEqx7t6MhoqWzs+g3K6BDPCDWmVAJF2kzXnYfryddiqhUabMleTIZiwdL+M8b4k5sgBKe+/Mgrp4gGrRH4okiz2rVmDcXpO8ET91QGI0VBERQfjf9ulS2oYXfouOXpjtQUqCTouL40RRKzZsVg2z7xycOQpReJWz5jcF78nv6BtRCfZH664/K+8oycyaWLHxHNXeZgkCPjTelAhubOTcb/n/gRVcBkj3Qfhoo3igEolyTkLCjH4dCxWk9Sir0awXlR/LuitPGeChFib6O1JLtEQYuo7edMvcYfb07L+Tyz8N6njeGv0vY1IAulGqne9rDpfUMaJKW/1I7Z1FnjzXkwgBrl4HQcdPPsl6HYsaxSZBbppSerkw5Eg="