language: java
sudo: false
dist: trusty

jdk:
  - openjdk11

cache:
  directories:
    - "$HOME/.m2"

install:
  - mvn --settings .travis/settings.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V

before_install:
    - if [ ! -z "$GPG_SECRET_KEYS" ]; then echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXEC --import; fi
    - if [ ! -z "$GPG_OWNERTRUST" ]; then echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXEC --import-ownertrust; fi

deploy:
  -
    provider: script
    script: mvn clean deploy --settings .travis/settings.xml -DskipTests=true -B -U
    on:
      branch: master